// Automatically generated by astro-icon
// ff69ed2eeecea3c7885803a191286188a0c82f19eab914de4260777f5dae66b2

declare module "virtual:astro-icon" {
    export type Icon =
        | "arrow-drop-down"
        | "clock-filled"
        | "close"
        | "facebook"
        | "flower"
        | "instagram"
        | "logo"
        | "menu"
        | "pepper"
        | "phone-filled"
        | "pin-filled"
        | "salt";
}
