services:
    backend:
        build:
            dockerfile: ./backend/Dockerfile
            target: production
        secrets:
            - PAYLOAD_SECRET
            - MONGO_PASSWORD
            - payload_root_password
        environment:
            - PORT=3456
            - FRONTEND_URL=http://frontend:7979
            - PAYLOAD_INIT_ROOT_PASSWORD_FILE=/run/secrets/payload_root_password
        volumes:
            - backend-storage:/app/backend/storage
        tmpfs:
            - /run/secrets
        depends_on:
            - database
        networks:
            back-network:
                aliases:
                    - backend
            front-network:
    database:
        secrets:
            - MONGO_PASSWORD
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/MONGO_PASSWORD
        volumes:
            - mongo-db:/data/db
            - mongo-db-config:/data/configdb
    database-setup:
        secrets:
            - MONGO_PASSWORD
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/MONGO_PASSWORD
    frontend:
        build:
            dockerfile: ./frontend/Dockerfile
            target: production
        volumes:
            - static-files:/app/frontend/result
        networks:
            back-network:
                aliases:
                    - frontend
        environment:
            - PUBLIC_API_URL=/api # Front network
    nginx:
        build:
            context: ./nginx
        volumes:
            - static-files:/data/www/
        environment:
            - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
            - CMS_URL=http://backend:3456
        networks:
            - front-network
            - back-network
volumes:
    backend-storage:
    mongo-db:
    mongo-db-config:
    static-files:
secrets:
    payload_root_password:
        file: ./payload_root_password.secret
    PAYLOAD_SECRET:
        file: ./payload_secret.secret
    MONGO_PASSWORD:
        file: ./mongo_password.secret
networks:
    back-network:
        driver: bridge
        internal: true
    front-network:
        driver: bridge
        internal: false
