/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
    collections: {
        users: User;
        "payload-preferences": PayloadPreference;
        "payload-migrations": PayloadMigration;
    };
    globals: {
        menu: Menu;
        contact_info: ContactInfo;
    };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
    id: string;
    role: "admin" | "staff" | "public";
    updatedAt: string;
    createdAt: string;
    email: string;
    resetPasswordToken?: string | null;
    resetPasswordExpiration?: string | null;
    salt?: string | null;
    hash?: string | null;
    loginAttempts?: number | null;
    lockUntil?: string | null;
    password: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
    id: string;
    user: {
        relationTo: "users";
        value: string | User;
    };
    key?: string | null;
    value?:
        | {
              [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
    id: string;
    name?: string | null;
    batch?: number | null;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu".
 */
export interface Menu {
    id: string;
    categories: {
        category_name: string;
        main_items?:
            | {
                  item: string;
                  price: number;
                  id?: string | null;
              }[]
            | null;
        sub_categories?:
            | {
                  sub_category_name: string;
                  sub_category_items: {
                      item: string;
                      price: number;
                      id?: string | null;
                  }[];
                  id?: string | null;
              }[]
            | null;
        id?: string | null;
    }[];
    updatedAt?: string | null;
    createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_info".
 */
export interface ContactInfo {
    id: string;
    phone_numbers: {
        phone_number: number;
        id?: string | null;
    }[];
    email: string;
    address: string;
    google_maps_link: string;
    updatedAt?: string | null;
    createdAt?: string | null;
}
