// Automatically generated by astro-icon
// 0826ebc2e055490fc9d4f59ad17aafc763c02a32b41d41477c820af2ad6b4a4d

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arrow-drop-down"
		| "cadre-edge-lg"
		| "cadre-edge-sm"
		| "clock-filled"
		| "close"
		| "facebook"
		| "flower"
		| "instagram"
		| "logo"
		| "mail"
		| "menu"
		| "pepper"
		| "phone-filled"
		| "pin-filled"
		| "salt";
}