// Automatically generated by astro-icon
// 82029b4768120eb5af89df94b8e45dde2d139bcfe8bd6d83adcb2c7f3142c246

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arrow-drop-down"
		| "cadre-edge-lg"
		| "cadre-edge-sm"
		| "clock-filled"
		| "close"
		| "facebook"
		| "flower"
		| "instagram"
		| "logo"
		| "menu"
		| "pepper"
		| "phone-filled"
		| "pin-filled"
		| "salt";
}