// Automatically generated by astro-icon
// 6e0bf9de644af6e46b6f2d3bc3a993d863aad254930d5368593debec172a4a51

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arrow-drop-down"
		| "cadre-edge"
		| "clock-filled"
		| "close"
		| "facebook"
		| "flower"
		| "instagram"
		| "logo"
		| "menu"
		| "pepper"
		| "phone-filled"
		| "pin-filled"
		| "salt";
}